import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />
        <div className="min-h-screen flex flex-col md:flex-row">
          {/* Sidebar di kiri pada desktop, navbar atas pada mobile */}
          <div className="w-full md:min-h-screen md:w-1/6">
            <Navbar />
          </div>
          <main className="bg-white text-black p-4 w-full md:w-5/6 min-h-screen">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
